refactor: use nullish coalescing
w3c/respec pull request #3624
Opened 2021-06-12 15:14 UTC by marcoscaceres

2021-06-12 16:00 UTC, marcoscaceres commented
Test failing because of #3626

2021-06-14 08:08 UTC, sidvishnoi commented on src/core/xref.js
> +          const specs = xref.specs?.concat(profiles[profile]) ?? [];
The result is not the same here.

2021-06-14 08:09 UTC, sidvishnoi requested changes

2021-06-14 08:09 UTC, sidvishnoi commented on src/core/xref.js
> +          const specs = xref.specs?.concat(profiles[profile]) ?? [];
The result is not the same here.

2021-06-14 08:39 UTC, marcoscaceres commented on src/core/xref.js
> +          const specs = xref.specs?.concat(profiles[profile]) ?? [];
ah, right.

2021-06-14 14:48 UTC, sidvishnoi approved these changes
Would love to find more potential uses and create a larger PR 😄

2021-06-15 01:26 UTC, merged