WIP: WTP integration
w3c/respec pull request #3870
Opened 2021-11-09 04:00 UTC by marcoscaceres

Work in progress to show WPT results and addition to caniuse. 

cc @sideshowbarker

2021-11-09 05:54 UTC, sideshowbarker commented on src/w3c/wpt.js
> +  // Gett the run ids first
```suggestion
  // Get the run ids first
```

2021-11-16 09:07 UTC, mera15 requested changes
profiles/w3c.js
wpt-results

2021-11-19 10:15 UTC, jhonmurga reviewed
``

2021-12-02 05:54 UTC, marcoscaceres commented
Problem we still have is some features only being exposed on particular platforms/os combinations… see Web Share API, which is on Firefox Windows and Android. Similarly, for Chrome: only supported on Android. 

Not much we can do about that, as wpt.fyi doesn’t test every platform combo… but it makes things a little messy/confusing for somebody that doesn’t know.

2024-04-27 04:51 UTC, closed without merging