BREAKING CHANGE(core/caniuse): new browser compat header
w3c/respec pull request #4075
Opened 2022-03-10 08:56 UTC by marcoscaceres

Closes #4042

2022-03-10 10:03 UTC, sidvishnoi requested changes

2022-03-10 10:03 UTC, sidvishnoi commented on src/core/caniuse.js
> +  const msg = `Couldn't find feature "${options.feature}".`;
This is assuming 404. It could be 50x too.

2022-03-10 22:26 UTC, marcoscaceres commented on src/core/caniuse.js
> +  const msg = `Couldn't find feature "${options.feature}".`;
```suggestion
  const msg = `Failed to retrieve feature "${options.feature}".`;
```

2022-03-10 22:28 UTC, marcoscaceres commented on src/core/caniuse.js
> +    const title = capitalize(`${supportLevel} in ${browserName}.`);
Sadly, that makes the capitalization of the `ariaLabel` wrong.

2022-03-10 22:29 UTC, marcoscaceres commented on tests/spec/core/caniuse-spec.js
> +    expect(cell.getAttribute("area-label")).toBe(
```suggestion
    expect(cell.getAttribute("aria-label")).toBe(
```

2022-03-10 23:09 UTC, marcoscaceres commented
Taking as is, as I need to record a video that uses it.

2022-03-10 23:09 UTC, merged

2022-03-11 10:53 UTC, sidvishnoi commented on src/core/caniuse.js
> +    const title = capitalize(`${supportLevel} in ${browserName}.`);
Should use "since" instead of "in" I think.

2022-03-11 10:56 UTC, sidvishnoi commented on src/core/caniuse.js
> +    const ariaLabel = `${feature} is ${supportLevel} in ${browserName}.`;
Firefox a11y panel shows it like this:
![image](https://user-images.githubusercontent.com/8426945/157854029-623d57cc-a810-42c1-bf23-e79ddacb403f.png)

Should test it out with Voiceover/NVDA

2022-03-11 10:57 UTC, sidvishnoi commented on src/core/caniuse.js
> +  const url = new URL(apiURL || `./${feature}`, API_URL);
I think we wanted:
```suggestion
  const url = new URL(`./${feature}`, apiURL || API_URL);
```