refactor(w3c/level): improve method docs
w3c/respec pull request #4623
Opened 2023-12-28 03:59 UTC by marcoscaceres

2023-12-28 06:35 UTC, sidvishnoi commented
I'm not finding the benefit of this particular class of refactor. How does typescript help here?

2023-12-29 04:27 UTC, marcoscaceres commented
The `LocalizationStrings` helps remind us to add all the appropriate languages. So, although it's not super useful here, it's going to be useful in other places where we have localization language gaps.

2024-01-06 13:36 UTC, sidvishnoi requested changes
I'm in favor of grouping all these PRs into bigger chunks.

Nits to be followed:
1. Make this comment appear in one line.
   ```diff
   - /**
   - * @type {LocalizationStrings}
   - */
   + /** @type {LocalizationStrings} */
   ```
2. Remove this "Localization data based on the user's language preference." comment as it's noisy.

2024-01-06 13:36 UTC, sidvishnoi commented on src/w3c/level.js
> + * @type {{ level: string }}
This type cast removes benefits of TS here I think.

2024-01-09 04:54 UTC, marcoscaceres commented on src/w3c/level.js
> + */
```suggestion
/** @type {LocalizationStrings} */
```

2024-04-09 03:39 UTC, sidvishnoi approved these changes

2024-04-09 06:27 UTC, merged